# Disable template caching for development hot-reloading
spring.thymeleaf.cache=false

# Server Port Configuration
server.port=8080

# ==========================================
# CẤU HÌNH KẾT NỐI SUPABASE (POSTGRESQL)
# ==========================================

# 1. Dùng port 6543 (Supabase Pooler) thay vì 5432 để tránh bị chặn bởi firewall
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres

# 2. Tài khoản mặc định (kèm theo mã dự án khi dùng Pooler để hỗ trợ mạng IPv4)
spring.datasource.username=postgres.ustnundvxlmxrxdavbym

# 3. Nhớ thay đúng mật khẩu dự án Supabase
spring.datasource.password=Hongquan@123

spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Ép trực tiếp Dialect để Hibernate không cần phải tự dò qua metadata nữa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Các cấu hình bổ sung hỗ trợ debug
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 6. Cấu hình timeout để app không bị treo khi DB không kết nối được
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=5

# ==========================================
# CẤU HÌNH GMAIL SMTP
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# spring.mail.username=hongquanvjp@gmail.com
# spring.mail.password=mrtv gdrw reep tmzp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.mail.username=${SPRING_MAIL_USERNAME:hongquanvjp@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:mrtv gdrw reep tmzp}